CREATE TABLE meal_items (
  -- PRIMARY KEY
  item_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  -- FOREIGN KEY
  meal_id INTEGER NOT NULL REFERENCES meals(meal_id) ON DELETE CASCADE,

  weight INTEGER,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)